---

- name: systemd daemon reload
  systemd:
    daemon_reload: yes
    scope: "{{ galaxy_systemd_root | ternary(omit, 'user') }}"

- name: galaxy systemd start
  systemd:
    name: galaxy.service
    state: started
    scope: "{{ galaxy_systemd_root | ternary(omit, 'user') }}"
  when: "galaxy_systemd_mode == 'gravity'"
  listen: "start galaxy"

- name: galaxy mule restart
  systemd:
    name: galaxy.service
    state: restarted
    scope: "{{ galaxy_systemd_root | ternary(omit, 'user') }}"
  when: "galaxy_systemd_mode == 'mule'"
  listen: "restart galaxy"
