---

- name: Create local storage read-only root
  file:
    path: "{{ galaxy_local_ro_root }}"
    owner: "{{ galaxy_privsep_user_name }}"
    group: "{{ galaxy_group_name }}"
    state: directory
    mode: "{{ galaxy_local_ro_root_mode | default('0750') }}"

- name: Create local storage read-only subdirectories
  file:
    path: "{{ item }}"
    owner: "{{ galaxy_privsep_user_name }}"
    group: "{{ galaxy_group_name }}"
    state: directory
    mode: "{{ galaxy_local_ro_root_mode | default('0750') }}"
  loop: "{{ galaxy_local_ro_dirs }}"
  when: item.startswith(galaxy_local_ro_root) ~ '/'
