---

- name: Deploy Galaxy Unit
  template:
    owner: "{{ galaxy_systemd_root | ternary('root', omit) }}"
    group: "{{ galaxy_systemd_root | ternary('root', omit) }}"
    mode: 0644
    src: galaxy.service.j2
    dest: "{{ galaxy_systemd_root | ternary('/etc/systemd/system/', ('~' ~ galaxy_user_name ~ '/.config/systemd/user') | expanduser) }}/galaxy.service"
  notify:
    - systemd daemon reload
    - start galaxy
    - restart galaxy

- name: Enable Galaxy service unit
  systemd:
    name: galaxy.service
    enabled: yes
    scope: "{{ galaxy_systemd_root | ternary(omit, 'user') }}"
