---

- name: Deploy Galaxy systemd service unit
  template:
    owner: root
    group: root
    mode: 0644
    src: galaxy.service.j2
    dest: /etc/systemd/system/galaxy.service
  notify:
    - systemd daemon reload
    - systemd galaxy restart

- name: Enable Galaxy systemd service Unit
  systemd:
    name: galaxy.service
    enabled: yes
