---
# handlers for gravity as used in galaxy version 23.0

- name: galaxyctl update
  command: "{{ galaxy_gravity_command }} -c {{ galaxy_config_file }} update"
  environment:
    GRAVITY_STATE_DIR: "{{ galaxy_gravity_state_dir }}"
  listen: "galaxyctl update"

- name: galaxy gravity restart
  command: "{{ galaxy_gravity_command }} -c {{ galaxy_config_file }} graceful"
  environment:
    GRAVITY_STATE_DIR: "{{ galaxy_gravity_state_dir }}"
  listen: "restart galaxy"
