---

- name: Include Gravity handlers (for 22.05)
  import_tasks:
    file: gravity_22.05.yml
  when: "galaxy_systemd_mode == 'gravity' and __galaxy_major_version is version('23.0', '<')"

- name: Include Gravity handlers (for 23.0)
  import_tasks:
    file: gravity_23.0.yml
  when: "galaxy_systemd_mode == 'gravity' and __galaxy_major_version is version('23.0', '>=')"
