---

- name: Create Galaxy virtualenv
  pip:
    name: pip
    virtualenv: "{{ galaxy_venv_dir }}"
    extra_args: "{{ pip_extra_args | default(omit) }}"
    virtualenv_command: "{{ galaxy_virtualenv_command | default(pip_virtualenv_command | default(omit)) }}"
    virtualenv_python: "{{ galaxy_virtualenv_python | default(omit) }}"

- name: Ensure pip is the desired release
  pip:
    name: pip
    state: "{{ galaxy_pip_version | default('latest') }}"
    extra_args: "{{ pip_extra_args | default(omit) }}"
    virtualenv: "{{ galaxy_venv_dir }}"
    virtualenv_command: "{{ galaxy_virtualenv_command | default(pip_virtualenv_command | default(omit)) }}"

- name: Ensure setuptools is latest working release (<58)
  pip:
    # FIXME: still necessary?
    #name: setuptools<58
    name: setuptools
    #state: present
    state: latest
    extra_args: "{{ pip_extra_args | default(omit) }}"
    virtualenv: "{{ galaxy_venv_dir }}"
    virtualenv_command: "{{ galaxy_virtualenv_command | default(pip_virtualenv_command | default(omit)) }}"
