---
# Manage Galaxy framework dependencies

- name: Install Galaxy base dependencies
  pip:
    requirements: "{{ galaxy_requirements_file }}"
    extra_args: "{{ pip_extra_args | default(omit) }}"
    virtualenv: "{{ galaxy_venv_dir }}"
    virtualenv_command: "{{ galaxy_virtualenv_command | default(pip_virtualenv_command | default(omit)) }}"
  environment:
    VIRTUAL_ENV: "{{ galaxy_venv_dir }}"

- name: Collect Galaxy conditional dependency requirement strings
  command: "{{ galaxy_venv_dir }}/bin/python -c \"import galaxy.dependencies; print('\\n'.join(galaxy.dependencies.optional('{{ galaxy_config_file }}')))\""
  environment:
    PYTHONPATH: "{{ galaxy_server_dir }}/lib"
  register: conditional_dependencies
  changed_when: no

- name: Install Galaxy conditional dependencies
  pip:
    name: "{{ conditional_dependencies.stdout_lines }}"
    extra_args: "--index-url https://wheels.galaxyproject.org/ --extra-index-url https://pypi.org/simple {{ pip_extra_args | default('') }}"
    virtualenv: "{{ galaxy_venv_dir }}"
    virtualenv_command: "{{ galaxy_virtualenv_command | default(pip_virtualenv_command | default(omit)) }}"
  environment:
    PYTHONPATH: null
    VIRTUAL_ENV: "{{ galaxy_venv_dir }}"
  when: (not ansible_check_mode) and conditional_dependencies.stdout_lines | length > 0

- name: Install additional packages into galaxy's virtual environment
  pip:
    name: "{{ galaxy_additional_venv_packages }}"
    virtualenv: "{{ galaxy_venv_dir }}"
    virtualenv_command: "{{ galaxy_virtualenv_command | default(pip_virtualenv_command | default(omit)) }}"
  environment:
    PYTHONPATH: null
    VIRTUAL_ENV: "{{ galaxy_venv_dir }}"
  when: galaxy_additional_venv_packages

- name: Configure $GRAVITY_STATE_DIR in virtualenv activate
  blockinfile:
    path: "{{ galaxy_venv_dir }}/bin/activate"
    marker: "# {mark} GALAXYPROJECT.GALAXY ROLE ANSIBLE MANAGED BLOCK"
    block: |
      # Galaxy Gravity per-instance state directory configured by galaxyproject.galaxy Ansible role
      GRAVITY_STATE_DIR={{ galaxy_gravity_state_dir | quote }}
      export GRAVITY_STATE_DIR
