---

- name: Gravity setup (Gravity < 1)
  environment:
    GRAVITY_STATE_DIR: "{{ galaxy_gravity_state_dir }}"
  when: __galaxy_major_version is version('23.0', '<')
  block:

    - name: Register Galaxy config with Gravity (Gravity < 1)
      command: "{{ galaxy_gravity_command }} register {{ galaxy_config_file }}"
      args:
        creates: "{{ galaxy_gravity_state_dir }}/configstate.yaml"

- name: Deploy galaxyctl wrapper script
  copy:
    content: |
      #!/usr/bin/env sh
      export GRAVITY_CONFIG_FILE={{ galaxy_config_file | quote }}
      exec {{ galaxy_gravity_command | quote }} "$@"
    dest: "{{ galaxy_gravity_wrapper_path }}"
    mode: "0755"
  when: galaxy_gravity_wrapper_path is not none
