---
# defaults for roles in the galaxyproject.galaxy collection

# User that Galaxy runs as
# TODO: describe dict keys
galaxy_user: "{{ ansible_user_id }}"

# User that owns Galaxy code, configs, and virutalenv, and that runs `pip install` for dependencies
galaxy_privsep_user: root

# TODO: this wording doesn't make it clear what you should do depending on your deployment scenario
# No explicit group is created by default, system policy will decide users' groups. However, in order to enable
# privilege separation without making configs world-readable, the users should share a common group. This group will be
# created if it does not exist. Ideally this is the primary group of `galaxy_user`, on most Linux systems, just set this
# to the same value as `galaxy_user` if you want to enable this feature.
# TODO: should automatically determine this in the case that it's not specified, rather than assuming it's the username
galaxy_group: "{{ galaxy_user_name }}"

# Because galaxy_user and galaxy_user_name vars can be either a bare username or a dict
galaxy_user_name: "{{ galaxy_user.name | default(galaxy_user) }}"
galaxy_privsep_user_name: "{{ galaxy_privsep_user.name | default(galaxy_privsep_user) }}"
galaxy_group_name: "{{ (galaxy_group | default({})).name | default(galaxy_group) }}"

# Should the Galaxy user and group be created
galaxy_create_user: true
galaxy_create_group: true

# If the privsep user is not root it will also be created, but you can override this behavior
galaxy_create_privsep_user: "{{ galaxy_privsep_user_name != 'root' }}"





# Gonna attempt path handling here
galaxy_local_root: "{{ galaxy_root }}/local"
galaxy_shared_root: "{{ galaxy_root }}/share"
galaxy_local_ro_root: "{{ galaxy_local_root }}/ro"
galaxy_shared_ro_root: "{{ galaxy_shared_root }}/ro"
galaxy_local_rw_root: "{{ galaxy_local_root }}/rw"
galaxy_shared_rw_root: "{{ galaxy_shared_root }}/rw"

galaxy_config_dir: "{{ galaxy_local_ro_root }}/config"

galaxy_venv_dir: "{{ galaxy_shared_ro_root }}/venv"
galaxy_server_dir: "{{ galaxy_shared_ro_root }}/server"
galaxy_local_tools_dir: "{{ galaxy_shared_ro_root }}/local_tools"

galaxy_mutable_data_dir: "{{ galaxy_local_rw_root }}/lib"
galaxy_mutable_config_dir: "{{ galaxy_local_rw_root }}/lib/config"
galaxy_cache_dir: "{{ galaxy_local_rw_root }}/tmp/cache"

galaxy_shed_tools_dir: "{{ galaxy_shared_rw_root }}/lib/shed_tools"
galaxy_tool_dependency_dir: "{{ galaxy_shared_rw_root }}/lib/dependencies"
galaxy_file_path: "{{ galaxy_shared_rw_root }}/lib/objects"
galaxy_new_file_path: "{{ galaxy_shared_rw_root }}/tmp/scratch"
galaxy_job_working_directory: "{{ galaxy_shared_rw_root }}/tmp/jobs"

galaxy_local_ro_dirs:
  - "{{ galaxy_config_dir }}"

galaxy_shared_ro_dirs:
  - "{{ galaxy_local_tools_dir }}"

galaxy_local_rw_dirs:
  - "{{ galaxy_mutable_data_dir }}"
  - "{{ galaxy_mutable_config_dir }}"
  - "{{ galaxy_cache_dir }}"

galaxy_shared_rw_dirs:
  - "{{ galaxy_shed_tools_dir }}"
  - "{{ galaxy_tool_dependency_dir }}"
  - "{{ galaxy_file_path }}"
  - "{{ galaxy_new_file_path }}"
  - "{{ galaxy_job_working_directory }}"

# TODO: ftp, object store cache, ???

# Control whether to output verbose task diffs (e.g. when performing a git update) when running Ansible with --diff.
# Only suppresses diff on tasks that are likely to be verbose, not all tasks
galaxy_diff_mode_verbose: "{{ ansible_diff_mode }}"

# Local (relative to playbook) path to local tools
galaxy_local_tools_src_dir: files/galaxy/tools

# Local (relative to playbook) path to dynamic job rules
galaxy_dynamic_job_rules_src_dir: files/galaxy/dynamic_job_rules

# Remote path to dynamic job rules (must be on Galaxy's $PYTHONPATH if not the default)
galaxy_dynamic_job_rules_dir: "{{ galaxy_server_dir }}/lib/galaxy/jobs/rules"

# List of dynamic rules to install
galaxy_dynamic_job_rules: []

#
# Version control
#

# This is now automatically determined in tasks/_inc_node_version.yml, but it can be set to force a version
#galaxy_node_version: "XX.YY.Z"

# Where to clone Galaxy from. Backwards compatibility with galaxy_git_repo
galaxy_repo: "{{ galaxy_git_repo | default('https://github.com/galaxyproject/galaxy.git') }}"

# Automatically delete things in the repo that do not belong there
galaxy_force_checkout: no

# Git clone depth for the galaxy repository. Leave unset to ignore.
#galaxy_clone_depth:

# This can be a tag (as shown here) but doing so will cause the revision check task to always report "changed".
# Backwards compatibility with galaxy_changeset_id.
galaxy_commit_id: "{{ galaxy_changeset_id | default('master') }}"

# Download URL (if used)
galaxy_download_url: "{{ galaxy_repo | replace('.git', '') }}/archive/{{ galaxy_commit_id }}.tar.gz"

#
# Path and Galaxy configuration
#

# Directory layout for deployment (legacy is the default)
#galaxy_layout: legacy

# List of tool configs to load
galaxy_tool_config_files:
  - "{{ galaxy_server_dir }}/config/tool_conf.xml.sample"

# The shed tool conf path is needed separate from the value of tool_conf for instantiation. The 'conf' version is a
# legacy variable name and should not be used.
galaxy_shed_tool_conf_file: "{{ galaxy_mutable_config_dir }}/shed_tool_conf.xml"
galaxy_shed_tool_config_file: "{{ galaxy_shed_tool_conf_file }}"

# The Python `requirements.txt` file that should be used to install Galaxy dependent modules using pip
galaxy_requirements_file: "{{ galaxy_server_dir }}/lib/galaxy/dependencies/pinned-requirements.txt"

# This will be configurable at some point
galaxy_static_dir: "{{ galaxy_server_dir }}/static"

# Galaxy config file can either be 'ini-paste' (old style) or 'yaml'
galaxy_config_style: "yaml"
galaxy_config_file_basename: "galaxy.{{ 'yml' if galaxy_config_style in ('yaml', 'yml') else 'ini' }}"
galaxy_config_file_template: "{{ galaxy_config_file_basename }}.j2"
galaxy_config_file: "{{ galaxy_config_dir }}/{{ galaxy_config_file_basename }}"
galaxy_app_config_section: "{{ 'galaxy' if galaxy_config_style in ('yaml', 'yml') else 'app:main' }}"

# Whether to back up config files before overwriting: default depends on whether --diff is used.
# galaxy_backup_configfiles is read for legacy purposes.
galaxy_backup_config_files: "{{ galaxy_backup_configfiles | default(not ansible_diff_mode) }}"

# Galaxy configuration files will be written with these permissions (mode argument to Ansible copy/template module)
galaxy_config_perms: 0640


# The default Galaxy configuration, ensures that Galaxy can find all of the configs if galaxy_config_dir !=
# galaxy_server_dir
galaxy_paste_app_factory: "galaxy.web.buildapp:app_factory"
galaxy_app_config_default:
  # Defaults for sample configs that require a value to be set
  builds_file_path: "{{ galaxy_server_dir }}/tool-data/shared/ucsc/builds.txt.sample"
  data_manager_config_file: "{{ galaxy_server_dir }}/config/data_manager_conf.xml.sample"
  datatypes_config_file: "{{ galaxy_server_dir }}/config/datatypes_conf.xml.sample"
  external_service_type_config_file: "{{ galaxy_server_dir }}/config/external_service_types_conf.xml.sample"
  openid_config_file: "{{ galaxy_server_dir }}/config/openid_conf.xml.sample"
  ucsc_build_sites: "{{ galaxy_server_dir }}/tool-data/shared/ucsc/ucsc_build_sites.txt.sample"
  tool_data_table_config_path: "{{ galaxy_server_dir }}/config/tool_data_table_conf.xml.sample"
  tool_sheds_config_file: "{{ galaxy_server_dir }}/config/tool_sheds_conf.xml.sample"

  # Various cache and temporary directories
  data_dir: "{{ galaxy_mutable_data_dir }}"

  # Mutable config files
  integrated_tool_panel_config: "{{ galaxy_mutable_config_dir }}/integrated_tool_panel.xml"
  migrated_tools_config: "{{ galaxy_mutable_config_dir }}/migrated_tools_conf.xml"
  shed_data_manager_config_file: "{{ galaxy_mutable_config_dir }}/shed_data_manager_conf.xml"
  shed_tool_data_table_config: "{{ galaxy_mutable_config_dir }}/shed_tool_data_table_conf.xml"

  # Directories that would often be stored outside the mutable data dir, these values are either from the layout or set by the user
  file_path: "{{ galaxy_file_path }}"
  job_working_directory: "{{ galaxy_job_working_directory }}"
  tool_dependency_dir: "{{ galaxy_tool_dependency_dir }}"

  # Static config files
  tool_config_file: "{{ galaxy_tool_config_files | join(',') }}"
  shed_tool_config_file: "{{ galaxy_shed_tool_config_file }}"

  # Everything else
  visualization_plugins_directory: "config/plugins/visualizations"

# Need to set galaxy_config_default[galaxy_app_config_section] dynamically but Ansible/Jinja2 does not make this easy
galaxy_config_default: "{{ {} | combine({galaxy_app_config_section: galaxy_app_config_default}) }}"
galaxy_config_merged: "{{ galaxy_config_default | combine(galaxy_config | default({}), recursive=True) }}"

# Automatically instantiate mutable config files from copies in role if they don't exist
galaxy_mutable_config_files:
  - src: "shed_data_manager_conf.xml"
    dest: "{{ galaxy_config_merged[galaxy_app_config_section].shed_data_manager_config_file }}"
  - src: "shed_tool_data_table_conf.xml"
    dest: "{{ galaxy_config_merged[galaxy_app_config_section].shed_tool_data_table_config }}"
galaxy_mutable_config_templates:
  - src: "shed_tool_conf.xml.j2"
    dest: "{{ galaxy_config_merged[galaxy_app_config_section].migrated_tools_config }}"
  - src: "shed_tool_conf.xml.j2"
    dest: "{{ galaxy_shed_tool_config_file }}"

galaxy_config_error_email_to: "{{ galaxy_config_merged[galaxy_app_config_section].error_email_to | default('') }}"
galaxy_config_instance_resource_url: "{{ galaxy_config_merged[galaxy_app_config_section].instance_resource_url | default('') }}"
galaxy_errordocs_server_name: Galaxy
galaxy_errordocs_prefix: /error

# These are lists of hashes in the same format as galaxy_mutable_configs that can be used to cause extra files and
# templates to be installed on the managed host.
galaxy_config_files: []
galaxy_config_templates: []

# Default uWSGI configuration
galaxy_uwsgi_yaml_parser: internal
galaxy_uwsgi_config_default:
  http: 127.0.0.1:8080
  buffer-size: 16384
  processes: 1
  threads: 4
  offload-threads: 2
  static-map:
    - /static/style={{ galaxy_server_dir }}/static/style/blue
    - /static={{ galaxy_server_dir }}/static
  master: true
  virtualenv: "{{ galaxy_venv_dir }}"
  pythonpath: "{{ galaxy_server_dir }}/lib"
  module: galaxy.webapps.galaxy.buildapp:uwsgi_app()
  thunder-lock: true
  die-on-term: true
  hook-master-start:
    - unix_signal:2 gracefully_kill_them_all
    - unix_signal:15 gracefully_kill_them_all
  py-call-osafterfork: true
  enable-threads: true

# TODO: Implement something like this for starter/restarter
#galaxy_server_type: paste_singleprocess

#
# Client build settings
#

# Options include: client / client-production / client-production-maps (default). Set to null to invoke each step of the
# build separately, but this is not guaranteed to work for all version of Galaxy - using `make` is the safer choice.
galaxy_client_make_target: client-production-maps

# If galaxy_client_make_target is null, you can set this to `development` to build the client for development
galaxy_client_node_env: production
galaxy_client_build_steps:
  default:
    - client
    - plugins
  "19.09":
    - fonts
    - stageLibs
    - plugins


# Restart handler is already set if using the systemd options in this role, otherwise you need to define one yourself
galaxy_manage_systemd: false
# FIXME: document, implement for Gravity
galaxy_restart_handler_name: "{{ 'systemd galaxy restart' if (galaxy_systemd_mode == 'mule' and galaxy_manage_systemd) else 'default restart galaxy handler' }}"

#
# systemd options
#

# Currently `mule` is the only systemd mode
galaxy_systemd_mode: mule

# Systemd will create cgroups to enforce these limits (sizes in GB), override individual limits by setting
# `galaxy_systemd_memory_limit.<limit>` in your vars.
__galaxy_systemd_memory_limit:
  # This is for the entire group of uWSGI master, web worker, and mule processes
  mule: 16
  reports: 5
  #workflow: 5
  #zergpool: 8
  #zergling: 16
  #handler: 5
__galaxy_systemd_memory_limit_merged: "{{ __galaxy_systemd_memory_limit | combine(galaxy_systemd_memory_limit | default({})) }}"

# A list of KEY=val strings to be added as `Environment=KEY=val` to the systemd service unit
galaxy_systemd_env: []

# A list of additional python packages to install into galaxy's virtual environment
galaxy_additional_venv_packages: []
